/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_cognito_identity_pool_id": "ca-central-1:6caff98b-cd88-4792-b199-161e5deabbd1",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_72AvhBx7V",
    "aws_user_pools_web_client_id": "314ca2pa0o0f7lk5a3nkoga45j",
    "oauth": {}
};


export default awsmobile;
